# This New Version workflow is manually triggered and will update the version based on your inputs
name: New Version
on:
  workflow_dispatch:  # Go to [Actions] - select New Version -> [Run workflow]
    inputs:
      release_type:
        description: '[major/minor/patch]'
        default: 'patch'
        required: true
jobs:
  update-semver:
    runs-on: ubuntu-latest
    steps:
    - name: clone PR branch
      uses: actions/checkout@master
      with:
        fetch-depth: 1
        path: new_version

    - name: clone base branch
      uses: actions/checkout@master
      with:
        fetch-depth: 1
        path: base
        ref: ${{ '{{' }} github.event.pull_request.base.sha {{ '}}' }}

    - name: setup-python
      id: setup-python
      uses: actions/setup-python@master

    - name: install-bumpversion
      id: install-bumpversion
      run: |
        pip install bump2version

    - name: bump-version
      id: bump-version
      working-directory: new_version
      run: |
        CUR_VER=$(grep "current_version = " ../base/setup.cfg|cut -d " " -f3)
        git config user.name = github-actions
        git config user.email = github-actions@github.com
        bumpversion --current-version ${CUR_VER} ${{ '{{' }} github.event.inputs.release_type {{ '}}' }} --no-tags
        NEW_VER=$(grep "current_version = " setup.cfg|cut -d " " -f3)
        if [[ $NEW_VER > $CUR_VER ]]; then
            echo "All good!"; else
            echo "New version is not greater than current version!"
            exit 1
        fi
        git push -f --no-verify
