# See https://pre-commit.com/ for usage and config
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: no-commit-to-branch
    name: Check not master branch
    args: ['--branch', 'master']
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: detect-aws-credentials
    args: ['--allow-missing-credentials']
  - id: detect-private-key
  - id: end-of-file-fixer
    exclude: docs/|setup.cfg
  - id: trailing-whitespace
    exclude: docs/|setup.cfg

- repo: https://github.com/myint/docformatter
  rev: v1.5.0 # v1.5.1 gives unwanted formatting behaviour relating to https://github.com/PyCQA/docformatter/issues/124, please use v1.5.0 until a new stable release patches this
  hooks:
  - id: docformatter

- repo: https://github.com/humitos/mirrors-autoflake
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
      - id: flake8
        types: [python]
        exclude: setup.py
        additional_dependencies: [
            'flake8-blind-except',
            'flake8-comprehensions',
            'flake8-deprecated',
            'flake8-docstrings',
            'flake8-meiqia',
            'flake8-mutable',
            'flake8-pep3101',
            'flake8-quotes',
            'flake8-string-format',
            'flake8-tidy-imports',
        ]
        args: ['--ignore=E203,E266,E501,W503', '--max-line-length=88', '--max-complexity=18', '--select=B,C,E,F,W,T4']

- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
      - id: isort
        args: ['--multi-line=3', '--trailing-comma', '--force-grid-wrap=0', '--use-parentheses', '--line-length=88']

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
      - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.990
  hooks:
      - id: mypy
        exclude: docs/|setup.py|tests/
        args: [--no-strict-optional, --install-types, --non-interactive, --ignore-missing-imports, --disallow-untyped-defs]
        require_serial: true

- repo: local
  hooks:
  - id: add inits
    name: add_inits
    language: system
    entry: bash -c \
      "for DIR in $(find \"./{{ cookiecutter.repo_name }}\" -type d); do
        touch $DIR/__init__.py;
      done"

- repo: https://github.com/anmut-consulting/pipenv-setup
  rev: v3.1.5
  hooks:
  - id: pipenv-setup-sync
    stages: [push]

  - id: pipenv-setup-check
    stages: [push]
