# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    types: [ assigned, edited, opened, ready_for_review, reopened, synchronize ]
    branches: [ main, master ] 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  basics_install:
    # Run on a BigSur machine
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # First clone the branch involved in the PR
    - name: clone PR branch
      uses: actions/checkout@master
      with:
        fetch-depth: 1
        path: pull_request
        ref: ${{ github.event.pull_request.head.ref }}
        
    - name: run basics.sh
      id: basics-install
      run: |
        cd ~/pipenv-cookiecutter
        chmod +x basics.sh
        /bin/bash basics.sh

      

